if (NOT DEFINED TOOLCHAIN_PATH)
	message(FATAL_ERROR "TOOLCHAIN_PATH is not defined")
endif()

set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER_WORKS true)
set(CMAKE_CXX_COMPILER_WORKS true)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}/bin/x86_64-elf-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}/bin/x86_64-elf-g++)
set(CMAKE_LINKER ${TOOLCHAIN_PATH}/bin/x86_64-elf-ld)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(TARGET_COMPILE_OPTIONS -mcmodel=kernel -mno-red-zone)

execute_process(
	COMMAND ${CMAKE_CXX_COMPILER} -print-file-name=crtbegin.o
	OUTPUT_VARIABLE CRTBEGIN
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND ${CMAKE_CXX_COMPILER} -print-file-name=crtend.o
	OUTPUT_VARIABLE CRTEND
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
	COMMAND x86_64-elf-gcc --print-file-name=libgcc.a
	OUTPUT_VARIABLE LIBGCC
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
